<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU</Platforms>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ryujinx.Common\Ryujinx.Common.csproj" />
    <ProjectReference Include="..\Ryujinx.Graphics.GAL\Ryujinx.Graphics.GAL.csproj" />
    <ProjectReference Include="..\Ryujinx.Memory\Ryujinx.Memory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.SPIRV.Cross" />
    <PackageReference Include="Silk.NET.SPIRV.Cross.Native" />
    <PackageReference Include="Silk.NET.Shaderc" />
    <PackageReference Include="Silk.NET.Vulkan" />
  </ItemGroup>

</Project>
